name: Release Tag

on:
  workflow_run:
    workflows: [Java CI with Gradle]
    types:
      - completed

permissions: write-all

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
          echo 'The triggering workflow passed'
          echo ${{ github.event.head_commit.message }}
          echo ${{ toJSON(github.event) }}