name: Java CI with Gradle

on:
  push:
    branches:
      - '**'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  tag:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: release -Prelease.overriddenBranchName=${{ github.head_ref }}
      - name: Get version
        id: version
        run: |
          echo VERSION=$( ./gradlew cV -q -Prelease.quiet ) >> $GITHUB_ENV
      - run: gh release create v$VERSION--generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: stephanepaulus
          password: ${{ secrets.DOCKER_HUB_PSW }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jib