name: release-published

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Send greeting
        run: echo "Hello world"


          

